### ISSUE TITLE
glue.addr does not work android/armeabi

### ISSUE THREAD

**Issue by fastcoding** [luapower/glue#2]
when I used this module and pthread bindings on android phone (32bit, armeabi), I got segment fault error when creating pthread. 

```
local function addr32(p)
	return tonumber(ffi.cast(intptr_ct, ffi.cast(voidptr_ct, p)))
end
```
casting  intptr_ct to number will result in a sign result. for example, on the phone I tested with pthread, the pointer 0xb6e083b0 will become 0xffffffffb6e083b0.

the correct one should be 

```
local uint32_ct=typeof'uint32_t'
...
return tonumber(ffi.cast(uint32_ct,ffi.cast(intptr_ct, ffi.cast(voidptr_ct, p)))
```
pthread_test.lua should be also updated to require glue.addr than use a local version.

**Comment by capr** [comment]
On my 32bit Windows machine, `print(glue.addr(ffi.cast('void*', 0xb6e083b0)))` prints `-1226800208`. And `print(glue.ptr(-1226800208))` prints `cdata<void *>: 0xb6e083b0`. So what's going on? Is your Lua number type `double` ? Is your `intptr_ct` `int32_t`? Is your `sizeof'void*'` 4 ?

**Comment by fastcoding** [comment]
yes, LUA_NUMBER_DOUBLE is defined in luaconf.h, and all intptr_ct, int32_t and void* are 4 bytes.
I tried this line on a 32bit x86-linux machine. I got  the same result:
```
>
> print(string.format('%x',-1))
ffffffffffffffff
> print(ffi.sizeof('void*'))         
4
```
Here is how to reproduce it: 
```
mac:luapower user$ scp  glue.lua luajit_h.lua lua_h.lua pthread.lua luastate.lua pthread_test.lua  user@x86linux:~/temp
```
comment the line require 'pp' from pthread_test.lua
then run luajit

```
user@x86linux:~/temp$ luajit pthread_test.lua
priority range: 	0	0
creating many threads 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 1 2 3 4 5 6 7 8 9 10 
mutex trylocks:
	thread 	1	316985
	thread 	2	464057
double free or corruption (fasttop)
aborted
```

**Comment by capr** [comment]
What does `print(glue.addr(ffi.cast('void*', 0xb6e083b0)))` print? what does `ffi.abi'64bit'` print?

**Comment by fastcoding** [comment]
> print(glue.addr(ffi.cast('void*', 0xb6e083b0)))
-1226800208
> print(ffi.abi'64bit')
false

**Comment by capr** [comment]
and `print(glue.ptr(-1226800208))` ?

**Comment by fastcoding** [comment]
> print(glue.ptr(-1226800208))
cdata<void *>: 0xb6e083b0

back to the same address. this is correct result.

**Comment by capr** [comment]
Then the problem is elsewhere. Most probably on the cdefs for the pthread types. Note that 1) luapower doesn't support android and none of the packages were written/built/tested on android, and 2) pthread ABI (thus struct definitions) is totally incompatible between platforms, so you'll have to check/cdef those cdefs for android.

**Comment by capr** [comment]
Curious why it fails on your `32bit x86-linux` though. Just tested on mine (ubuntu 14.04) and it works.

**Comment by fastcoding** [comment]
but how to explain I got the basically the same crash on x86linux?

**Comment by capr** [comment]
dunno, you've got to debug this yourself since I can't reproduce...

**Comment by fastcoding** [comment]
ok thanks,  I will find out later.  anyway, after patched cdef from NDK, the pthread already looks work on android, though it still crashes on my x86-linux, I guess there might hide other unknown issue in patched version.
