### ISSUE TITLE
Removal of `glue.tuples`

### ISSUE THREAD

**Issue by Vaskivo** [luapower/glue#3]
What was the reasoning for removing the `tuples` from this library?

I could use your `tuple` project, but you say it is deprecated.

**Comment by capr** [comment]
The reason is because you can achieve the same with the follwing:

```
local function tuple()
	return glue.memoize(function(...) return {} end)
end 
```

**Comment by Vaskivo** [comment]
(Just to leave a solution here for anyone who wants it...)

I believe that code isn't quite right.
Don't you mean:
```lua
local tuple = glue.memoize(function(...) return {} end)
```

**Comment by capr** [comment]
Sorry for my terse response. Yes, I guess my function should've been called `tuplespace` or `tuples` and called like `local tuple = tuplespace()`.

So
```
local function tuplespace()
	return glue.memoize(function(...) return {} end)
end 
local tuple = tuplespace()
```
